interface FormatInfo {
  extensions: string[];
  mimeTypes: string[];
  description: string;
  strengths: string;
  limitations: string;
  compatibleSoftware: string;
  typicalUseCases: string;
  sizeCharacteristics: string;
}

const FORMAT_INFO: Record<string, FormatInfo> = {
  pdf: { extensions: ['.pdf'], mimeTypes: ['application/pdf'], description: 'Portable Document Format - universal document standard', strengths: 'Preserves exact layout across all devices, print-ready, secure with password protection, universally viewable', limitations: 'Difficult to edit without specialized tools, larger file sizes when containing images', compatibleSoftware: 'Adobe Acrobat, Foxit Reader, Chrome, Edge, Preview (Mac)', typicalUseCases: 'Contracts, reports, forms, ebooks, print documents', sizeCharacteristics: 'Usually 50-200KB per page, increases with embedded images' },
  docx: { extensions: ['.docx'], mimeTypes: ['application/vnd.openxmlformats-officedocument.wordprocessingml.document'], description: 'Microsoft Word Open XML Document - modern Word format', strengths: 'Editable, widely supported, compact file size, supports rich formatting and media', limitations: 'Formatting may vary across different Word versions or alternative editors', compatibleSoftware: 'Microsoft Word, Google Docs, LibreOffice, Apple Pages', typicalUseCases: 'Business documents, letters, resumes, academic papers', sizeCharacteristics: 'Typically 10-100KB for text, increases with embedded media' },
  doc: { extensions: ['.doc'], mimeTypes: ['application/msword'], description: 'Legacy Microsoft Word Document format', strengths: 'Long-established format, wide compatibility with older software', limitations: 'Larger file size than DOCX, limited features compared to DOCX, binary format', compatibleSoftware: 'Microsoft Word, Google Docs, LibreOffice, Apple Pages', typicalUseCases: 'Legacy documents, archives, compatibility with older systems', sizeCharacteristics: 'Typically larger than DOCX for same content' },
  odt: { extensions: ['.odt'], mimeTypes: ['application/vnd.oasis.opendocument.text'], description: 'OpenDocument Text - open standard document format', strengths: 'Open standard, royalty-free, good for long-term preservation, supported by many free editors', limitations: 'Less compatible with Microsoft Office, some formatting may be lost in Office', compatibleSoftware: 'LibreOffice, OpenOffice, Google Docs, Microsoft Word', typicalUseCases: 'Open-source environments, government documents, long-term archives', sizeCharacteristics: 'Similar to DOCX in size' },
  rtf: { extensions: ['.rtf'], mimeTypes: ['application/rtf', 'text/rtf'], description: 'Rich Text Format - cross-platform formatted text', strengths: 'Universally readable, simple formatting, works across all platforms', limitations: 'Limited formatting support, no advanced features, large file size compared to modern formats', compatibleSoftware: 'WordPad, Microsoft Word, TextEdit, almost any word processor', typicalUseCases: 'Simple formatted text, cross-platform compatibility, legacy system integration', sizeCharacteristics: 'Can be 2-3x larger than DOCX for same content' },
  txt: { extensions: ['.txt'], mimeTypes: ['text/plain'], description: 'Plain Text - simplest document format with no formatting', strengths: 'Universal, smallest file size, works everywhere, human-readable', limitations: 'No formatting, no images, no tables, no structure beyond plain text', compatibleSoftware: 'Notepad, TextEdit, VS Code, any text editor', typicalUseCases: 'Code, logs, data import, minimal documents', sizeCharacteristics: 'Smallest format - 1KB per 100 words' },
  pptx: { extensions: ['.pptx'], mimeTypes: ['application/vnd.openxmlformats-officedocument.presentationml.presentation'], description: 'Microsoft PowerPoint Presentation - modern format', strengths: 'Rich media support, animations, professional templates, widely used', limitations: 'Requires PowerPoint or compatible viewer, large with embedded media', compatibleSoftware: 'Microsoft PowerPoint, Google Slides, LibreOffice Impress, Apple Keynote', typicalUseCases: 'Business presentations, lectures, pitch decks, training materials', sizeCharacteristics: 'Varies widely - 50KB to 50MB depending on media content' },
  ppt: { extensions: ['.ppt'], mimeTypes: ['application/vnd.ms-powerpoint'], description: 'Legacy Microsoft PowerPoint format', strengths: 'Long-established, wide compatibility', limitations: 'Larger files, fewer features than PPTX, binary format', compatibleSoftware: 'Microsoft PowerPoint, Google Slides, LibreOffice Impress', typicalUseCases: 'Legacy presentations, archives', sizeCharacteristics: 'Similar to PPTX' },
  odp: { extensions: ['.odp'], mimeTypes: ['application/vnd.oasis.opendocument.presentation'], description: 'OpenDocument Presentation format', strengths: 'Open standard, royalty-free, good for long-term use', limitations: 'Less widely used, compatibility issues with PowerPoint', compatibleSoftware: 'LibreOffice Impress, OpenOffice, Google Slides', typicalUseCases: 'Open-source presentations, government presentations, archives', sizeCharacteristics: 'Similar to PPTX' },
  xlsx: { extensions: ['.xlsx'], mimeTypes: ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'], description: 'Microsoft Excel Spreadsheet - modern format', strengths: 'Powerful formulas, charts, pivot tables, data analysis, widely used', limitations: 'Can be large with many sheets, some features only in Excel', compatibleSoftware: 'Microsoft Excel, Google Sheets, LibreOffice Calc, Apple Numbers', typicalUseCases: 'Financial data, analysis, reporting, data collection, databases', sizeCharacteristics: '10KB to several MB depending on data volume' },
  xls: { extensions: ['.xls'], mimeTypes: ['application/vnd.ms-excel'], description: 'Legacy Microsoft Excel format', strengths: 'Long-established, wide compatibility', limitations: 'Row/column limits, fewer features than XLSX, binary format', compatibleSoftware: 'Microsoft Excel, Google Sheets, LibreOffice Calc', typicalUseCases: 'Legacy spreadsheets, archives', sizeCharacteristics: 'Similar to XLSX' },
  ods: { extensions: ['.ods'], mimeTypes: ['application/vnd.oasis.opendocument.spreadsheet'], description: 'OpenDocument Spreadsheet format', strengths: 'Open standard, free, good for collaboration', limitations: 'Less feature-rich than Excel, compatibility issues', compatibleSoftware: 'LibreOffice Calc, OpenOffice, Google Sheets', typicalUseCases: 'Open-source spreadsheet work, government data', sizeCharacteristics: 'Similar to XLSX' },
  csv: { extensions: ['.csv'], mimeTypes: ['text/csv'], description: 'Comma-Separated Values - pure data format', strengths: 'Universal, smallest size, works with any data tool, human-readable', limitations: 'No formatting, no multiple sheets, no formulas', compatibleSoftware: 'Excel, Google Sheets, Python, R, any data processing tool', typicalUseCases: 'Data export/import, API responses, database dumps, analysis', sizeCharacteristics: 'Smallest spreadsheet format - pure text' },
  epub: { extensions: ['.epub'], mimeTypes: ['application/epub+zip'], description: 'Electronic Publication - open ebook standard', strengths: 'Reflowable text, widely supported by e-readers, open standard', limitations: 'Not easily editable, DRM may restrict usage, limited print output', compatibleSoftware: 'Apple Books, Google Play Books, Kindle (converted), Adobe Digital Editions', typicalUseCases: 'Ebooks, digital publications, manuals, guides', sizeCharacteristics: 'Typically 200KB to 5MB' },
  mobi: { extensions: ['.mobi'], mimeTypes: ['application/x-mobipocket-ebook'], description: 'Mobipocket ebook format', strengths: 'Amazon Kindle compatible, compact, good reading experience', limitations: 'Proprietary, limited device support outside Kindle, being phased out', compatibleSoftware: 'Amazon Kindle, Kindle apps, Calibre', typicalUseCases: 'Kindle ebooks, personal document archive', sizeCharacteristics: 'Similar to EPUB' },
  azw: { extensions: ['.azw'], mimeTypes: ['application/vnd.amazon.mobi8-ebook'], description: 'Amazon Kindle proprietary format', strengths: 'Optimized for Kindle devices, DRM support, Amazon ecosystem', limitations: 'Proprietary, locked to Amazon ecosystem, limited compatibility', compatibleSoftware: 'Amazon Kindle devices and apps only', typicalUseCases: 'Amazon Kindle Store books, Kindle personal documents', sizeCharacteristics: 'Similar to EPUB' },
  html: { extensions: ['.html', '.htm'], mimeTypes: ['text/html'], description: 'HyperText Markup Language - web standard', strengths: 'Universal web standard, interactive, embeddable, SEO-friendly', limitations: 'Not ideal for print, security concerns with scripts, requires browser', compatibleSoftware: 'Chrome, Firefox, Safari, Edge, any web browser', typicalUseCases: 'Web pages, email templates, documentation, interactive content', sizeCharacteristics: 'Typically 5-50KB for standard pages' },
  md: { extensions: ['.md'], mimeTypes: ['text/markdown'], description: 'Markdown - lightweight markup language', strengths: 'Human-readable, version-control friendly, converts to many formats, simple syntax', limitations: 'Limited formatting compared to rich text, no built-in layout control', compatibleSoftware: 'VS Code, GitHub, Notion, Obsidian, any text editor', typicalUseCases: 'Documentation, READMEs, blogs, notes, technical writing', sizeCharacteristics: 'Very small - pure text with minimal markup' },
  jpg: { extensions: ['.jpg', '.jpeg'], mimeTypes: ['image/jpeg'], description: 'JPEG - compressed image format', strengths: 'Small file size, universal support, good for photographs, widely used', limitations: 'Lossy compression, no transparency, quality degrades with repeated edits', compatibleSoftware: 'Any image viewer, web browsers, Photoshop, GIMP', typicalUseCases: 'Photographs, web images, social media, documents with photos', sizeCharacteristics: 'Typically 50KB to 5MB depending on quality' },
  png: { extensions: ['.png'], mimeTypes: ['image/png'], description: 'Portable Network Graphics - lossless image', strengths: 'Lossless compression, transparency support, good for graphics, sharp text', limitations: 'Larger than JPEG for photos, not ideal for print (no CMYK)', compatibleSoftware: 'Any image viewer, web browsers, Photoshop, GIMP', typicalUseCases: 'Logos, screenshots, graphics, UI elements, transparent images', sizeCharacteristics: 'Typically larger than JPEG for same visual content' },
  webp: { extensions: ['.webp'], mimeTypes: ['image/webp'], description: 'WebP - modern Google image format', strengths: 'Superior compression, smaller than JPEG/PNG, supports transparency and animation', limitations: 'Not universally supported by older software, limited editing tool support', compatibleSoftware: 'Chrome, Firefox, Edge, Photoshop (with plugin)', typicalUseCases: 'Web images, responsive design, fast-loading websites', sizeCharacteristics: '25-35% smaller than JPEG/PNG equivalents' },
  tiff: { extensions: ['.tiff', '.tif'], mimeTypes: ['image/tiff'], description: 'Tagged Image File Format - professional imaging', strengths: 'Lossless, high quality, editable without degradation, metadata support', limitations: 'Very large file sizes, not web-friendly, overkill for casual use', compatibleSoftware: 'Adobe Photoshop, GIMP, professional photography software', typicalUseCases: 'Professional photography, scanning, archival, print production', sizeCharacteristics: 'Can be 10-100MB per image' },
  bmp: { extensions: ['.bmp'], mimeTypes: ['image/bmp'], description: 'Bitmap - uncompressed image', strengths: 'Simple format, universally readable, no compression artifacts', limitations: 'Extremely large files, no compression, no transparency', compatibleSoftware: 'Windows Paint, any image viewer, basic graphics tools', typicalUseCases: 'Legacy graphics, simple image storage, raw image data', sizeCharacteristics: 'Largest image format - unused pixels still take space' },
};

export function getFormatInfo(format: string): FormatInfo {
  return FORMAT_INFO[format.toLowerCase()] || {
    extensions: [`.${format}`],
    mimeTypes: [],
    description: `${format.toUpperCase()} format`,
    strengths: 'Supported by various applications',
    limitations: 'May require specific software',
    compatibleSoftware: 'Various applications that support this format',
    typicalUseCases: 'Document exchange and storage',
    sizeCharacteristics: 'Varies based on content',
  };
}

export function generateUniqueContent(sourceFormat: string, targetFormat: string): string {
  const source = getFormatInfo(sourceFormat);
  const target = getFormatInfo(targetFormat);

  return [
    `## How ${sourceFormat.toUpperCase()} to ${targetFormat.toUpperCase()} Conversion Works`,
    `Our free online converter transforms your ${sourceFormat.toUpperCase()} (${source.description}) files into ${targetFormat.toUpperCase()} (${target.description}) format, preserving document quality throughout the conversion process. Drop your file into the upload zone above and click convert — no registration, no watermarks, no credits required.`,
    `## What Happens to Your Formatting`,
    `When converting from ${sourceFormat.toUpperCase()} to ${targetFormat.toUpperCase()}, the conversion engine preserves as much formatting as possible. ${source.strengths} All of these elements are mapped to their closest equivalents in the ${targetFormat.toUpperCase()} format. ${target.limitations} Our AI-enhanced conversion intelligently handles edge cases to maintain the highest possible quality.`,
    `## Expected Quality and File Size`,
    `The conversion quality depends on the complexity of your source document. Simple text-based ${sourceFormat.toUpperCase()} documents convert near-perfectly to ${targetFormat.toUpperCase()}. Complex documents with embedded media, custom fonts, or advanced formatting may see minor variations. ${source.sizeCharacteristics} After conversion, ${target.sizeCharacteristics}`,
    `## Common Use Cases`,
    `This ${sourceFormat.toUpperCase()} to ${targetFormat.toUpperCase()} converter is commonly used for: ${source.typicalUseCases}. Converting to ${targetFormat.toUpperCase()} is ideal when you need: ${target.typicalUseCases}.`,
    `## Compatible Software`,
    `Your ${sourceFormat.toUpperCase()} file can be opened with: ${source.compatibleSoftware}. Your converted ${targetFormat.toUpperCase()} file will be compatible with: ${target.compatibleSoftware}.`,
    `## Limitations and Considerations`,
    `While our converter produces excellent results for most documents, be aware of the following: ${source.limitations} Additionally, ${targetFormat.toUpperCase()} has these inherent limitations: ${target.limitations}. For best results, ensure your source ${sourceFormat.toUpperCase()} file is well-formed and not corrupted. Our converter handles files up to 10MB in size.`,
  ].join('\n\n');
}

export function getPairContent(slug: string): string {
  const parts = slug.split('-to-');
  if (parts.length !== 2) return '';
  return generateUniqueContent(parts[0], parts[1]);
}
